# Generated by Django 5.2.8 on 2025-12-16 08:55

import app2_rendering_task.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "app1_model_management",
            "0006_alter_category_options_alter_category_model_type",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RenderingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "render_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="渲染任务的唯一标识",
                        unique=True,
                        verbose_name="渲染ID",
                    ),
                ),
                (
                    "render_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="渲染时间"
                    ),
                ),
                (
                    "sun_azimuth",
                    models.FloatField(
                        default=0.0,
                        help_text="阳光照射的方位角（0°-360°）",
                        validators=[app2_rendering_task.models.validate_azimuth],
                        verbose_name="日光方位角",
                    ),
                ),
                (
                    "sun_elevation",
                    models.FloatField(
                        default=90.0,
                        help_text="阳光照射的高低角（0°-90°）",
                        validators=[app2_rendering_task.models.validate_elevation],
                        verbose_name="日光高低角",
                    ),
                ),
                (
                    "camera_distances",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="相机到目标的距离列表（正值）",
                        validators=[
                            app2_rendering_task.models.validate_positive_number_list
                        ],
                        verbose_name="相机距离",
                    ),
                ),
                (
                    "camera_elevations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="相机高低角列表（0°-90°）",
                        validators=[app2_rendering_task.models.validate_elevation_list],
                        verbose_name="相机高低角",
                    ),
                ),
                (
                    "camera_rotation_step",
                    models.FloatField(
                        default=45.0,
                        help_text="相机方位角采样间隔（0°-360°）",
                        validators=[app2_rendering_task.models.validate_azimuth],
                        verbose_name="相机方位角间隔",
                    ),
                ),
                (
                    "image_width",
                    models.PositiveIntegerField(
                        default=1920, verbose_name="渲染图像分辨率（宽）"
                    ),
                ),
                (
                    "image_height",
                    models.PositiveIntegerField(
                        default=1080, verbose_name="渲染图像分辨率（高）"
                    ),
                ),
                (
                    "renderer_type",
                    models.CharField(
                        choices=[("EEVEE", "EEVEE"), ("CYCLES", "Cycles")],
                        default="EEVEE",
                        max_length=10,
                        verbose_name="渲染器类别",
                    ),
                ),
                (
                    "rendered_result",
                    models.FileField(
                        blank=True,
                        help_text="系统自动生成的渲染结果图像（只读）",
                        null=True,
                        upload_to=app2_rendering_task.models.rendered_result_path,
                        verbose_name="渲染图像地址",
                    ),
                ),
                (
                    "scene_models",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rendering_tasks",
                        to="app1_model_management.scenemodel",
                        verbose_name="场景模型",
                    ),
                ),
                (
                    "target_models",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rendering_tasks",
                        to="app1_model_management.targetmodel",
                        verbose_name="目标模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "01-渲染任务",
                "verbose_name_plural": "01-渲染任务",
                "ordering": ["-render_time"],
            },
        ),
    ]
