# Generated by Django 5.2.8 on 2025-12-16 11:20

import app2_rendering_task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2_rendering_task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="renderingtask",
            name="render_status",
            field=models.CharField(
                choices=[
                    ("pending", "未渲染"),
                    ("rendering", "正在渲染"),
                    ("completed", "完成渲染"),
                ],
                default="pending",
                help_text="渲染任务的当前状态",
                max_length=20,
                verbose_name="渲染状态",
            ),
        ),
        migrations.AlterField(
            model_name="renderingtask",
            name="camera_distances",
            field=models.JSONField(
                blank=True,
                default=[100],
                help_text="相机到目标的距离列表（正值）",
                validators=[app2_rendering_task.models.validate_positive_number_list],
                verbose_name="相机距离",
            ),
        ),
        migrations.AlterField(
            model_name="renderingtask",
            name="camera_elevations",
            field=models.JSONField(
                blank=True,
                default=[45],
                help_text="相机高低角列表（0°-90°）",
                validators=[app2_rendering_task.models.validate_elevation_list],
                verbose_name="相机高低角",
            ),
        ),
    ]
