# Generated by Django 5.2.8 on 2025-12-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2_rendering_task", "0002_renderingtask_render_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="renderingtask",
            name="render_status",
        ),
        migrations.AddField(
            model_name="renderingtask",
            name="render_progress",
            field=models.FloatField(
                default=0.0,
                help_text="渲染任务的进度百分比(0-100)",
                verbose_name="渲染进度",
            ),
        ),
    ]
