# Generated by Django 5.2.8 on 2025-12-18 07:34

import app2_rendering_task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app2_rendering_task",
            "0004_rename_rendered_result_renderingtask_rendered_result_dir",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="renderingtask",
            name="camera_elevations",
            field=models.JSONField(
                blank=True,
                default=[75],
                help_text="相机高低角列表（0°-90°）",
                validators=[app2_rendering_task.models.validate_elevation_list],
                verbose_name="相机高低角",
            ),
        ),
        migrations.AlterField(
            model_name="renderingtask",
            name="camera_rotation_step",
            field=models.FloatField(
                default=90,
                help_text="相机方位角采样间隔（0°-360°）",
                validators=[app2_rendering_task.models.validate_azimuth],
                verbose_name="相机方位角间隔",
            ),
        ),
        migrations.AlterField(
            model_name="renderingtask",
            name="render_progress",
            field=models.FloatField(
                default=0.0, help_text="渲染任务的进度(0-1)", verbose_name="渲染进度"
            ),
        ),
    ]
