# Generated by Django 5.2.8 on 2025-12-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1_model_management", "0010_scenemodel"),
        ("app2_rendering_task", "0001_initial_squashed_0006_renderingtask_render_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renderingtask",
            name="scene_models",
            field=models.ManyToManyField(
                blank=True,
                related_name="rendering_tasks",
                to="app1_model_management.scenemodel",
                verbose_name="场景模型",
            ),
        ),
    ]
