# Generated by Django 5.2.8 on 2025-12-23 03:26

import app2_rendering_task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2_rendering_task", "0007_alter_renderingtask_scene_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renderingtask",
            name="camera_distances",
            field=models.JSONField(
                blank=True,
                default=app2_rendering_task.models.default_camera_distances,
                help_text="相机到目标的距离列表（正值）",
                validators=[app2_rendering_task.models.validate_positive_number_list],
                verbose_name="相机距离",
            ),
        ),
        migrations.AlterField(
            model_name="renderingtask",
            name="camera_elevations",
            field=models.JSONField(
                blank=True,
                default=app2_rendering_task.models.default_camera_elevations,
                help_text="相机高低角列表（0°-90°）",
                validators=[app2_rendering_task.models.validate_elevation_list],
                verbose_name="相机高低角",
            ),
        ),
    ]
