# Generated by Django 5.2.8 on 2026-01-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2_rendering_task", "0008_alter_renderingtask_camera_distances_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renderingtask",
            name="render_type",
            field=models.SmallIntegerField(
                choices=[(0, "图像数据集"), (1, "点云数据集")],
                default=0,
                verbose_name="渲染类别",
            ),
        ),
    ]
