# Generated by Django 5.2.8 on 2026-01-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2_rendering_task", "0009_alter_renderingtask_render_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="renderingtask",
            name="render_name",
            field=models.CharField(
                default="渲染任务", max_length=50, verbose_name="任务名称"
            ),
        ),
    ]
