# Generated by Django 5.2.8 on 2025-12-02 11:57

import app1_model_management.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SceneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        editable=False,
                        max_length=36,
                        unique=True,
                        verbose_name="模型ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="模型所属的类别",
                        max_length=100,
                        verbose_name="模型类别",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="请上传 *.fbx 格式的3D模型文件",
                        upload_to=app1_model_management.models.scene_model_upload_path,
                        verbose_name="模型文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景模型",
                "verbose_name_plural": "场景模型",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TargetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        editable=False,
                        max_length=36,
                        unique=True,
                        verbose_name="模型ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="模型所属的类别",
                        max_length=100,
                        verbose_name="模型类别",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="请上传 *.fbx 格式的3D模型文件",
                        upload_to=app1_model_management.models.target_model_upload_path,
                        verbose_name="模型文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "目标模型",
                "verbose_name_plural": "目标模型",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
