# Generated by Django 5.2.8 on 2025-12-22 07:42

import app1_model_management.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("app1_model_management", "0001_initial"),
        (
            "app1_model_management",
            "0002_alter_scenemodel_options_alter_targetmodel_options_and_more",
        ),
        (
            "app1_model_management",
            "0003_alter_category_options_alter_scenemodel_options_and_more",
        ),
        (
            "app1_model_management",
            "0004_alter_scenemodel_category_alter_targetmodel_category",
        ),
        ("app1_model_management", "0005_category_model_type"),
        (
            "app1_model_management",
            "0006_alter_category_options_alter_category_model_type",
        ),
        (
            "app1_model_management",
            "0007_alter_scenemodel_model_id_alter_targetmodel_model_id",
        ),
        (
            "app1_model_management",
            "0008_alter_scenemodel_model_id_alter_targetmodel_model_id",
        ),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="层级"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="app1_model_management.category",
                        verbose_name="父级分类",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("target", "目标模型分类"),
                            ("scene", "场景模型分类"),
                            ("general", "通用分类"),
                        ],
                        default="target",
                        help_text="指定该分类适用于哪种模型类型",
                        max_length=10,
                        verbose_name="标签类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "01-分类标签",
                "verbose_name_plural": "01-分类标签",
                "ordering": ["model_type", "level", "name"],
            },
        ),
        migrations.CreateModel(
            name="SceneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="场景模型的唯一标识",
                        unique=True,
                        verbose_name="模型ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="请上传 *.fbx 格式的3D模型文件",
                        upload_to=app1_model_management.models.scene_model_upload_path,
                        verbose_name="模型文件",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        help_text="模型所属的类别",
                        to="app1_model_management.category",
                        verbose_name="模型类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "03-场景模型",
                "verbose_name_plural": "03-场景模型",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TargetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="目标模型的唯一标识",
                        unique=True,
                        verbose_name="模型ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="请上传 *.fbx 格式的3D模型文件",
                        upload_to=app1_model_management.models.target_model_upload_path,
                        verbose_name="模型文件",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        help_text="模型所属的类别",
                        to="app1_model_management.category",
                        verbose_name="模型类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "02-目标模型",
                "verbose_name_plural": "02-目标模型",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
