# Generated by Django 5.2.10 on 2026-01-19 03:27

import app1_model_management.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('target', '目标模型分类'), ('scene', '场景模型分类'), ('general', '通用分类')], default='target', help_text='指定该分类适用于哪种模型类型', max_length=10, verbose_name='标签类别')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('level', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='层级')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app1_model_management.category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '01-分类标签',
                'verbose_name_plural': '01-分类标签',
                'ordering': ['model_type', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SceneModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='场景模型的唯一标识', unique=True, verbose_name='模型ID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('file', models.FileField(help_text='请上传 *.blend/*.glb/*.fbx 格式的3D模型文件', upload_to=app1_model_management.models.scene_model_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['blend', 'glb', 'fbx'])], verbose_name='模型文件')),
                ('category', models.ManyToManyField(blank=True, help_text='模型所属的类别', to='app1_model_management.category', verbose_name='模型类别')),
            ],
            options={
                'verbose_name': '02-场景模型文件',
                'verbose_name_plural': '02-场景模型文件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SceneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='场景的唯一标识', unique=True, verbose_name='场景ID')),
                ('points', models.JSONField(blank=True, default=app1_model_management.models.default_points, help_text='场景模型控制点', verbose_name='控制点')),
                ('scene_model', models.ForeignKey(help_text='场景模型文件', on_delete=django.db.models.deletion.CASCADE, to='app1_model_management.scenemodelfile', verbose_name='场景模型')),
            ],
            options={
                'verbose_name': '03-场景模型',
                'verbose_name_plural': '03-场景模型',
                'ordering': ['scene_model', 'scene_id'],
            },
        ),
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='目标模型的唯一标识', unique=True, verbose_name='模型ID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('file', models.FileField(help_text='请上传 *.glb/*.fbx 格式的3D模型文件', upload_to=app1_model_management.models.target_model_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'fbx'])], verbose_name='模型文件')),
                ('category', models.ManyToManyField(blank=True, help_text='模型所属的类别', to='app1_model_management.category', verbose_name='模型类别')),
            ],
            options={
                'verbose_name': '04-目标模型',
                'verbose_name_plural': '04-目标模型',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
