# Generated by Django 5.2.8 on 2025-12-16 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1_model_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scenemodel",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "02-场景模型",
                "verbose_name_plural": "02-场景模型",
            },
        ),
        migrations.AlterModelOptions(
            name="targetmodel",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "01-目标模型",
                "verbose_name_plural": "01-目标模型",
            },
        ),
        migrations.RemoveField(
            model_name="scenemodel",
            name="category",
        ),
        migrations.RemoveField(
            model_name="targetmodel",
            name="category",
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="层级"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="app1_model_management.category",
                        verbose_name="父级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "ordering": ["level", "name"],
            },
        ),
        migrations.AddField(
            model_name="scenemodel",
            name="category",
            field=models.ManyToManyField(
                help_text="模型所属的类别",
                to="app1_model_management.category",
                verbose_name="模型类别",
            ),
        ),
        migrations.AddField(
            model_name="targetmodel",
            name="category",
            field=models.ManyToManyField(
                help_text="模型所属的类别",
                to="app1_model_management.category",
                verbose_name="模型类别",
            ),
        ),
    ]
