# Generated by Django 5.2.8 on 2025-12-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app1_model_management",
            "0002_alter_scenemodel_options_alter_targetmodel_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["level", "name"],
                "verbose_name": "01-分类",
                "verbose_name_plural": "01-分类",
            },
        ),
        migrations.AlterModelOptions(
            name="scenemodel",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "03-场景模型",
                "verbose_name_plural": "03-场景模型",
            },
        ),
        migrations.AlterModelOptions(
            name="targetmodel",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "02-目标模型",
                "verbose_name_plural": "02-目标模型",
            },
        ),
    ]
