# Generated by Django 5.2.8 on 2025-12-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app1_model_management",
            "0003_alter_category_options_alter_scenemodel_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenemodel",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                help_text="模型所属的类别",
                to="app1_model_management.category",
                verbose_name="模型类别",
            ),
        ),
        migrations.AlterField(
            model_name="targetmodel",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                help_text="模型所属的类别",
                to="app1_model_management.category",
                verbose_name="模型类别",
            ),
        ),
    ]
