# Generated by Django 5.2.8 on 2025-12-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app1_model_management",
            "0004_alter_scenemodel_category_alter_targetmodel_category",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("target", "目标模型"),
                    ("scene", "场景模型"),
                    ("general", "通用"),
                ],
                default="general",
                help_text="指定该分类适用于哪种模型类型",
                max_length=10,
                verbose_name="模型类型",
            ),
        ),
    ]
