# Generated by Django 5.2.8 on 2025-12-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1_model_management", "0005_category_model_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["model_type", "level", "name"],
                "verbose_name": "01-分类标签",
                "verbose_name_plural": "01-分类标签",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("target", "目标模型分类"),
                    ("scene", "场景模型分类"),
                    ("general", "通用分类"),
                ],
                default="target",
                help_text="指定该分类适用于哪种模型类型",
                max_length=10,
                verbose_name="标签类别",
            ),
        ),
    ]
