# Generated by Django 5.2.8 on 2025-12-16 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app1_model_management",
            "0006_alter_category_options_alter_category_model_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenemodel",
            name="model_id",
            field=models.UUIDField(
                default=uuid.UUID("5dbb149b-2233-449a-9db6-f78e9999dc17"),
                editable=False,
                help_text="场景模型的唯一标识",
                unique=True,
                verbose_name="模型ID",
            ),
        ),
        migrations.AlterField(
            model_name="targetmodel",
            name="model_id",
            field=models.UUIDField(
                default=uuid.UUID("cb9fd85f-47e0-4dd3-879c-ad99cb090299"),
                editable=False,
                help_text="目标模型的唯一标识",
                unique=True,
                verbose_name="模型ID",
            ),
        ),
    ]
