# Generated by Django 5.2.8 on 2025-12-18 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app1_model_management",
            "0007_alter_scenemodel_model_id_alter_targetmodel_model_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenemodel",
            name="model_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="场景模型的唯一标识",
                unique=True,
                verbose_name="模型ID",
            ),
        ),
        migrations.AlterField(
            model_name="targetmodel",
            name="model_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="目标模型的唯一标识",
                unique=True,
                verbose_name="模型ID",
            ),
        ),
    ]
