# Generated by Django 5.2.8 on 2025-12-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app1_model_management",
            "0001_initial_squashed_0008_alter_scenemodel_model_id_alter_targetmodel_model_id",
        ),
        ("app2_rendering_task", "0001_initial_squashed_0006_renderingtask_render_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SceneModel",
            new_name="SceneModelFile",
        ),
        migrations.AlterModelOptions(
            name="scenemodelfile",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "02-场景模型文件",
                "verbose_name_plural": "02-场景模型文件",
            },
        ),
        migrations.AlterModelOptions(
            name="targetmodel",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "04-目标模型",
                "verbose_name_plural": "04-目标模型",
            },
        ),
    ]
