# Generated by Django 5.2.8 on 2025-12-23 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1_model_management", "0009_rename_scenemodel_scenemodelfile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scene_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="场景的唯一标识",
                        unique=True,
                        verbose_name="场景ID",
                    ),
                ),
                (
                    "points",
                    models.JSONField(
                        blank=True,
                        default={"point1": [0, 0, 0], "point2": [0, 1, 0]},
                        help_text="场景模型控制点",
                        verbose_name="控制点",
                    ),
                ),
                (
                    "scene_model",
                    models.ForeignKey(
                        help_text="场景模型文件",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1_model_management.scenemodelfile",
                        verbose_name="场景模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "03-场景模型",
                "verbose_name_plural": "03-场景模型",
                "ordering": ["scene_model", "scene_id"],
            },
        ),
    ]
