# Generated by Django 5.2.8 on 2025-12-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1_model_management", "0010_scenemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenemodel",
            name="points",
            field=models.JSONField(
                blank=True,
                default=[[0, 0, 0], [0, 1, 0]],
                help_text="场景模型控制点",
                verbose_name="控制点",
            ),
        ),
    ]
