# Generated by Django 5.2.8 on 2025-12-23 03:25

import app1_model_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1_model_management", "0011_alter_scenemodel_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenemodel",
            name="points",
            field=models.JSONField(
                blank=True,
                default=app1_model_management.models.default_points,
                help_text="场景模型控制点",
                verbose_name="控制点",
            ),
        ),
    ]
