# Generated by Django 5.2.8 on 2026-01-07 00:42

import app1_model_management.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1_model_management", "0012_alter_scenemodel_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenemodelfile",
            name="file",
            field=models.FileField(
                help_text="请上传 *.blend 或 *.fbx 格式的3D模型文件",
                upload_to=app1_model_management.models.scene_model_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["blend", "fbx"]
                    )
                ],
                verbose_name="模型文件",
            ),
        ),
        migrations.AlterField(
            model_name="targetmodel",
            name="file",
            field=models.FileField(
                help_text="请上传 *.fbx 格式的3D模型文件",
                upload_to=app1_model_management.models.target_model_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["fbx"]
                    )
                ],
                verbose_name="模型文件",
            ),
        ),
    ]
